# Generated by Django 4.2.7 on 2023-11-27 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='movie',
            new_name='movies',
        ),
    ]
