# Generated by Django 4.2.7 on 2023-11-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_rename_movie_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='image',
            field=models.ImageField(default='dddd', upload_to='pics'),
            preserve_default=False,
        ),
    ]
