# Generated by Django 4.2.7 on 2024-02-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='Actors',
            field=models.CharField(max_length=250),
        ),
    ]
