# Generated by Django 4.2.7 on 2024-02-04 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MovieAPP', '0002_alter_movies_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='user',
            field=models.ForeignKey(default=-14, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='youtube_link',
            field=models.CharField(default='dsd', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movies',
            name='Release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
