# Generated by Django 4.2.7 on 2024-02-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviePROFILEAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Profile',
            field=models.ImageField(blank=True, upload_to='profile'),
        ),
    ]
