# Generated by Django 4.2.7 on 2024-03-09 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MoviePROFILEAPP', '0002_profile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Bio',
            field=models.CharField(default=-2012, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='DOB',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='Preference',
            field=models.CharField(default=12, max_length=250),
            preserve_default=False,
        ),
    ]
